### ISSUE TITLE
[TOGZHAN | CLAIRE | TONY] Nav Bar

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#1]
### Task Description: 
In "NavBar.jsx," create a React navbar component with the general layout of the picture below, with the [logo](https://drive.google.com/file/d/1HYfv16RFO_vxTqKRq4A4NWqpakkbFNe0/view?usp=sharing) and categories. Don't worry about font and the drop down components, but try to get some of the basic styling for things like  alignment placement. 
<img width="455" alt="Screenshot 2024-10-10 at 4 55 21 PM" src="https://github.com/user-attachments/assets/4e36270c-60a4-4ef6-b654-bde789bbeeb5">
Link the logo to "Home.jsx" (and make sure there's an accessibility tag), the About page to "About.jsx" and the Contact page to "Contact.jsx." Don't worry about creating those pages, as another team will work on that. Try your best to make the navbar responsive!

### References and Resources: 
[Figma Link](https://www.figma.com/design/BUQG6l438XONSN7aiqZLwX/Dillar-Academy?node-id=10-2&node-type=frame)
https://tailwindcss.com/docs/flex 

### Acceptance Criteria: 
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] Do the links lead to other pages (the URL should change)?
- [x] Does the logo have an accessibility alt tag when you hover over it?
- [x] Does the general styling look similar to the reference photo?
