### ISSUE TITLE
[FRANK | MADELINE] Contact - DB Connection

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#11]
### Task Description: 
When the user submits the contact form we want a record of their inquiry to be stored in the MongoDB database. 
Make an API endpoint that takes in the inquiry data from the contact form and send it to the database. We’re using Mongoose to help interact with the database, so you’ll need to create a Mongoose contact schema.
### References and Resources: 
Express docs: https://expressjs.com/en/guide/routing.html 
Mongoose docs: https://mongoosejs.com/docs/guide.html
MongoDB collection commands: https://www.mongodb.com/docs/manual/reference/method/js-collection/ 
Using Express with MongoDB and Mongoose: https://dev.to/franciscomendes10866/setup-mongodb-with-mongoose-and-express-4c58 
Async/await: https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016 
(Optional but helpful for debugging): https://apidog.com/blog/how-to-use-postman-for-api-testing/ 
### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] When the contact form is submitted, is there a new record in the database?
- [ ] Are the records accurate - do they display the correct information?
