### ISSUE TITLE
[DONATELLO | JOHN] User - DB Connection

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#12]
### Task Description: 
When a user logs in, we want to check if they actually have an account in the database. Make an API endpoint that takes the user data from the login form and checks if that user exists in the MongoDB database. If yes, display a success message in the console, and if not, display an error message. You can use the temporary user “Megan” in the database to test.
### References and Resources: 
Express docs: https://expressjs.com/en/guide/routing.html 
Mongoose docs: https://mongoosejs.com/docs/guide.html
MongoDB collection commands: https://www.mongodb.com/docs/manual/reference/method/js-collection/ 
Using Express with MongoDB and Mongoose: https://dev.to/franciscomendes10866/setup-mongodb-with-mongoose-and-express-4c58 
Async/await: https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016 
(Optional but helpful for debugging): https://apidog.com/blog/how-to-use-postman-for-api-testing/ 
### Acceptance Criteria: 
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] Are existing users successfully able to “login”?
- [x] If a user that doesn’t currently exist tries to log in, is there an error message?
