### ISSUE TITLE
[CLAIRE | FAHIM] Classes - DB Connection

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#13]
### Task Description: 
Create an API endpoint that retrieves all of the classes from the MongoDB database and displays all their information on the screen. Don’t worry too much about styling, just make sure all the information for each class is correctly displayed in its own little box/section. There are some temporary classes in the database you can test with.
### References and Resources: 
Express docs: https://expressjs.com/en/guide/routing.html 
Mongoose docs: https://mongoosejs.com/docs/
MongoDB collection commands: https://www.mongodb.com/docs/manual/reference/method/js-collection/ 
Using Express with MongoDB and Mongoose: https://dev.to/franciscomendes10866/setup-mongodb-with-mongoose-and-express-4c58 
Async/await: https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016 
(Optional but helpful for debugging): https://apidog.com/blog/how-to-use-postman-for-api-testing/ 
### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] Are each of the classes displayed in their own section?
- [ ] Is the information for each of the classes correct?
