### ISSUE TITLE
[SPENCER | DONATELLO] Basic Contact Form 

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#2]
### Task Description: 
In "Contact.jsx" create a contact page with the input fields: name, email (with validation), subject, and message. It should have a similar layout to the picture below, but don't worry too much about the details like font and colors because that will change later. 
<img width="625" alt="Screenshot 2024-10-11 at 6 13 08 PM" src="https://github.com/user-attachments/assets/56108207-0031-4a62-9ae6-6fcfdd904af1">
One thing to note is that the Figma doesn't have a submit button, but we would like this contact form to. On submitting the form, there should be an alert that prints out the values of each input.

### References and Resources
[Figma Link ](https://www.figma.com/design/BUQG6l438XONSN7aiqZLwX/Dillar-Academy?node-id=10-2&node-type=frame)
https://www.w3schools.com/tags/tag_input.asp

### Acceptance Criteria
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] If you enter an invalid email, there should be an error/you should not be able to submit
- [x] There should be an alert when you submit that prints the inputs
- [x] Does the general styling look similar to the reference photo?
