### ISSUE TITLE
[CLAIRE | DONATELLO | YI] Display Classes 

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#28]
### **Task Description:** 
It’s time to hit the books and work on classes! 📚

First, modify the existing class endpoint that Claire and Fahim worked on last sprint to return only the classes that match a certain filter (ie. return all classes that are level 1, all classes that are taught by this instructor, or both). To get the optional filters, we’re going to use query strings which are field-value pairs that appear after the ? in a URL (so for the previous examples: ?level=1, ?instructor=Ildana, and both at once would be ?level=1&instructor=Ildana). We can get the parameters easily using Express’s req.query object.
We don’t want to directly use user input as it can be a security issue and/or cause unexpected behavior, so we’ve written a function you can use to validate the queries. The `allowedFields` parameter should be an array of a class object's fields. Once you’ve done that you can safely use them to filter for classes! To test you can use Postman or visit the endpoint in a browser.

Once you’ve got the endpoint working, create a class component that pulls age group, instructor, and the schedule. Then fetch the classes and use the component to display them on the Classes.jsx page with the general layout of the image below:
<img width="480" alt="Screenshot 2024-11-02 at 5 59 08 PM" src="https://github.com/user-attachments/assets/2e3adb1d-465c-41cd-ab82-df71fd40a2c9">
You'll need a useEffect to display the classes when the page loads. For now, you can display all the classes but for a bonus, try adding query params to the frontend URL to filter the classes. This will also require editing the class fetch function in class-wrapper.js to take the query as a parameter. As usual, don’t worry too much about the exact fonts and colors, as long as you get the general formatting down.
Hint: Use the generic button Yi and Frank created in the first sprint for the Register button, it doesn’t have to have an action when clicked yet. 

### **References and Resources:** 
[Figma](https://www.figma.com/design/bQkMH2fS2NAYoWDlynDh1W/Dillar-Academy?node-id=0-1&node-type=canvas&t=Bc51gF67MRShWgkO-0)
Query Params in Express: 
https://www.educative.io/answers/what-is-reqquery-in-expressjs 
https://www.scaler.com/topics/expressjs-tutorial/express-query-params/ 
MongoDB find(): https://www.mongodb.com/docs/manual/reference/method/db.collection.find/
React useEffect Hook: https://react.dev/reference/react/useEffect 
(For the bonus) URLSearchParams: https://dev.to/sanjampreetsingh/simplifying-api-calls-with-urlsearchparams-and-fetch-8gn

### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] Does adding no query params return all the classes?
- [ ] Does using the query level=1 only return the level 1 classes?
- [ ] Does the class component look like the image above?
- [ ] (For the bonus) Does adding instructor=Ehtibar to the website URL only show the classes Ehtibar teaches?
