### ISSUE TITLE
[SPENCER | MADELINE] Password Requirements 

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#29]
### Task Description:
We only want secure passwords (#cybersecurity)! 

We'll use the typical password requirements (at least 10 characters that are a combination of uppercase and lowercase letters, numbers, and symbols), with visual feedback on the Signup page showing which are fulfilled and what's still missing. You have some flexibility in how you want to display this as long as the requirements are red while they aren’t fulfilled and green once they are and the colors change as the password is being typed. 
 
Here's a reminder of the requirements: 
> 1. at least 10 characters
> 2. at least 1 uppercase
> 3. at least 1 lowercase
> 4. at least 1 number
> 5. at least 1 symbol

The user should only be allowed to sign up if **all** the requirements are met, so until then the button to register should be disabled/unclickable.

### References and Resources: 
There are several ways to implement a password checklist, here are some ideas:
Regex: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions 
Using a package: https://www.npmjs.com/package/react-password-checklist 

### Acceptance Criteria: 
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] Are the password requirements listed on the Sign up page?
- [x] Do the password requirements change visually as they are fulfilled?
- [x] Is the sign up button only visible/clickable if all the password requirements are met?
