### ISSUE TITLE
[MADELINE | FAHIM] Basic Login Pages

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#3]
### Task Description:
You will create the two log-in forms! 
First, in "Login.jsx" create a login page with the text fields email and password. It should have a similar layout to the picture below, but don't worry too much about the details like font and colors because that will change later.
<img width="262" alt="Screenshot 2024-10-11 at 6 25 59 PM" src="https://github.com/user-attachments/assets/35cd5061-b1bb-460a-9b27-1b798a4bb2cb">
The "Sign up" should link to the second page you'll work on, called "Signup.jsx." It will be extremely similar but have the fields: username, email (with validation that it's valid), password, and retype password (with validation that they're the same). 
<img width="310" alt="Screenshot 2024-10-11 at 6 27 57 PM" src="https://github.com/user-attachments/assets/45fa6450-9d78-4f59-905d-465b0b955ca5">
Both forms don't need to send the information anywhere yet, but upon clicking the Login or Signup button, there should be an alert or popup that prints the values of each input. 

### References and Resources: 
[Figma Link](https://www.figma.com/design/BUQG6l438XONSN7aiqZLwX/Dillar-Academy?node-id=10-2&node-type=frame)
https://www.w3schools.com/tags/tag_input.asp

### Acceptance Criteria: 
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] If you enter an invalid email, there should be an error/you should not be able to submit
- [x] There should be an alert when you submit that prints the inputs
- [x] Does the general styling look similar to the reference photo?
- [ ] Does the "Sign up" in the Login page link to the Signup page and vice versa?
