### ISSUE TITLE
[ARYAA | TOGZHAN] Retrieve Users

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#32]
### Task Description:
Write an endpoint in server.js that gets all the users from the MongoDB database. The mongoose User Schema is already written, so all you need to do is set up the endpoint and query the database to get the users. Once you have the endpoint you can test that it works by visiting your endpoint in the browser or using Postman. 

For an optional challenge, fetch the users from the endpoint in the frontend and display them on a page (you can use the Classes page for now since it’s blank)!  You will need the useEffect React hook to do the challenge.

### References and Resources:
Express docs: https://expressjs.com/en/guide/routing.html 
Mongoose docs: https://mongoosejs.com/docs/
Using Mongoose with MongoDB: https://www.mongodb.com/developer/languages/javascript/getting-started-with-mongodb-and-mongoose/ 
MongoDB collection commands: https://www.mongodb.com/docs/manual/reference/method/js-collection/ 
Using Express with MongoDB and Mongoose: https://dev.to/franciscomendes10866/setup-mongodb-with-mongoose-and-express-4c58 
Async/await: https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016 
Using Postman: https://apidog.com/blog/how-to-use-postman-for-api-testing/ 
(For the bonus) React useEffect Hook: https://react.dev/reference/react/useEffect 

### Acceptance Criteria:
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] Does the endpoint correctly fetch all the users?
- [x] (Optional) Are all the users showing up on the page?
