### ISSUE TITLE
 [JOHN | FRANK] Routing

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#38]
### Task Description: 
We want to ensure that users are seeing the right pages and everyone isn’t seeing nonexistent pages. 
Set up additional routes in PageRoutes.jsx - we’ll be using the Wouter library (which is essentially a minimalist version of the React Router with modified syntax). First, add one for if a user tries to go to a page that doesn’t exist, in which case we want to display a Page Not Found. For example, if you add /sdfsd to the end of the URL, the current behavior is that nothing shows up, but set up a route so that PageNotFound.jsx shows up instead. The Page Not Found design looks like this:
<img width="704" alt="image" src="https://github.com/user-attachments/assets/7b8a3fab-526c-4aa0-98b3-f068f66ee739">

For the second route, when a user signs in, we want to redirect them to their specific user page (ie. student portal for students and admin portal for admins). After a user logs in, redirect them to the StudentPortal.jsx page if they are a student or AdminView.jsx page if they are an admin and display the user’s name on the page.

### Acceptance Criteria:
- [x] Does Page Not Found show up if navigating to http://localhost:5173/asdf (or anything equivalent)
- [x] When logging in with a student account does the page redirect to a student page saying their name?
- [x] When logging in with an admin account does the page redirect to an admin page saying their name?

### References and Resources:
Wouter docs: https://www.npmjs.com/package/wouter#component-api (specifically the Route, Switch, Redirect components and useLocation hook will be helpful)
