### ISSUE TITLE
 [FAHIM | TONY]  High Fidelity Class Page & Nav Bar

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#39]
### Task Description: 
You’ll be building out the first high-fidelity sections of the site! 
We want Classes.jsx to look as close to this as possible, this time including colors and the hover states (which are all on the Figma) (the dropdown will still open on click instead of on hover): 
![Browse Classes](https://github.com/user-attachments/assets/a7a63a3e-f9ad-463d-9c4c-9f2a8fd5c522)
Right now to navigate to the Classes page you have to go click on a level, or you can go to /classes/?level=[level_num] in the URL. This will show the classes for each specific level.
Styling wise, this will involve modifying the class component, level component, and general button component’s styling a bit. Don't worry about the level description or tags though, there is no data on that yet. Similarly, the data displayed doesn't exactly have to match, just work on getting the general styling close to the Figma. Prioritize the general layout - it's OK if you don't get the hover effects.

_Check with Megan before you start working on this ticket - it depends on work from the last sprint!_

### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] Are all the classes for the level displayed?
- [ ] Does the styling look like the Figma?

### References and Resources 
[Figma](https://www.figma.com/design/bQkMH2fS2NAYoWDlynDh1W/Dillar-Academy?node-id=20-100&node-type=frame&t=L39cgbtdhr3cLx1p-0) - ready for dev section
Flexbox: https://css-tricks.com/snippets/css/a-guide-to-flexbox/ 
URLSearchParams: https://dev.to/sanjampreetsingh/simplifying-api-calls-with-urlsearchparams-and-fetch-8gn
