### ISSUE TITLE
[YI | FRANK] Generic Button Styling

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#4]
### Task Description: 
In "Button.jsx" create a React button component that takes in two props: "label" and "isOutline." Using conditional styling in Tailwind, create a button where if "isOutline" is true, the button should be styled to look like the button on the right in the image below: 
<img width="176" alt="Screenshot 2024-10-11 at 6 36 56 PM" src="https://github.com/user-attachments/assets/a3b3ebb6-0d59-4c42-950f-24742e6fc09d">
Otherwise, the button should look like the one on the left in the picture. Don't worry about colors and fonts because they may change later on. Use the label prop to define what the button's label is.

References and Resources 
[Figma Link](https://www.figma.com/design/BUQG6l438XONSN7aiqZLwX/Dillar-Academy?node-id=10-2&node-type=frame)
https://medium.com/@rakeebnazar/template-literals-vs-reacts-curly-braces-a-comparison-and-common-misconception-71f675ebc2aa

Acceptance Criteria: 
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] Does the button label change when you change the value passed to the label prop?
- [x] If "isOutline" is true, is the button transparent with a border?
- [x] If "isOutline" is false, is the button filled with no border?
- [x] Does the general styling look somewhat similar to the reference photo?
