### ISSUE TITLE
[YI | MADELINE | TOGZHAN] Class Enrollment & Unenrollment - DB Connection

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#40]
### Task Description: 
One of the most important parts of a class management system is the student’s ability to…. manage their classes! 
A student’s classes in the database will be represented using an array containing the ObjectID of classes they’re enrolled in. Create two new components using the general Button component to make an “enroll” and “unenroll” button. We want this enrollment information to be reflected in the database, so when a user clicks on “enroll,” that class should be added to their class list in the database. “Unenroll” should behave similarly: clicking the button should remove the class from the user’s class list.
The student should also be listed in the class’s roster when they enroll in the class. The classes will also have an array containing the ObjectID of students in the class, but sign in isn’t implemented across the site yet so for now you can hardcode an ObjectID to insert into the class’s roster array. With unenrolling, the student ObjectID should be removed from the array, you can also use a hardcoded ID.

_Check with Megan before you start working on this ticket - it depends on work from the last sprint!_

### Acceptance Criteria: 
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] Is a class added to the user’s list when they enroll in the class?
- [x] Is a class removed from the user’s list when they unenroll in the class?
- [x] When enrolling in a class does an ObjectID get added to the class’s roster array?
- [x] When unenrolling from a class does an ObjectID get deleted from the class’s roster array?

### References and Resources: 
MongoDB collection commands: https://www.mongodb.com/docs/manual/reference/method/js-collection/ 
MongoDB ObjectID: https://www.mongodb.com/docs/manual/reference/method/ObjectId/
