### ISSUE TITLE
[CLAIRE | SPENCER] Welcome Page

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#41]
### Task Description: 
The first thing we want to a user to do when they come to the site is to set the language they want to use. 
We want to make a new welcome page where they select their preferred language from the language dropdown John and Tony created last sprint. Style this as closely to the image below as possible (colors and fonts are in the Figma):  
<img width="906" alt="Screenshot 2024-11-15 at 10 32 25 AM" src="https://github.com/user-attachments/assets/e269b6c0-8ec8-4821-85bc-5a729e974bee">
Don’t worry - this ticket isn’t only styling! We also don’t want to ask a user for their language selection every time they come to the page, especially if they’re just refreshing. To do that we can use localStorage, which allows us to store information on a site for if the user comes back to it! To view a site's localStorage, you can use Application tab in the Inspect tools:
<img width="491" alt="Screenshot 2024-11-09 at 2 25 48 PM" src="https://github.com/user-attachments/assets/96ec7827-b897-4d89-88f9-e521ec3a7c0a">
As you can see, one value we're storing is the user's preferred language through a key-value pair. Similarly, we can create a key to keep track of if a user visited the site. Then when a user opens the site we can check if the key doesn't exist, and if not we display the Welcome page and add the key. Otherwise if the key does exist the user is shown the Home page.

### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] Does the Welcome page show up if the user has never opened the site before? (you can test using a guest browser)
- [ ] Does the Home page show up if the user has opened the site before?
- [ ] Is the selected language reflected on the page (can be tested by looking at the heading on the about page)?

### References and Resources: 
[Figma](https://www.figma.com/design/bQkMH2fS2NAYoWDlynDh1W/Dillar-Academy?node-id=1-1771&node-type=canvas&t=zC4ldSHTX4RQNv0l-0) - ready for dev section 
Conditional rendering in React: https://www.freecodecamp.org/news/react-conditional-rendering/ 
Getting localStorage keys: https://www.freecodecamp.org/news/how-to-use-localstorage-with-react-hooks-to-set-and-get-items/
