### ISSUE TITLE
[SPENCER | JOHN] Contact Page Email Connection 

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#52]
### Task Description: 
📞📞📞
There are two things that should happen when someone submits a message on the contact form. The first is already done: we want to store their message in the database. The second is what you’ll be implementing: we want to send out an email to admin containing the user’s subject and message from the contact form. We’re going to be using the Nodemailer library, which allows us to send out emails from a backend endpoint. Modify the contact endpoint to also send an email from the user’s inputted email address to the admin’s email address with the form content. Bonus points if you format the email to look nice and not just be plain text. To do that you’ll want to pass in HTML to the html field of the email.

We also want to implement internationalization on this page. We’re using the i18next library with i18nexus, which is a site where we can add strings and they’ll be automatically translated using Google Translate. Each string is assigned a key which we can use to reference the translations in our code (we would definitely recommend reading/skimming the first reference for a more detailed description and images of how it all works). 
Go through the Contact page and for all text (including headers, paragraph text, input placeholders, and button text) create a key-value pair in i18nexus with the string (make sure the key name is somewhat descriptive), and replace the text in the code with the key. This is a little tedious, but once you change the language on the site using the dropdown, all the text on the page should now be in the language selected! Yay!

### Acceptance Criteria: 
- [x] Did you link the ticket/issue number with your branch using the pull request template?
- [x] Does submitting the contact form send and email?
- [x] When changing the language, does all the text on the Contact page change to be in that language?

### References and Resources:
Nodemailer: 
https://www.nodemailer.com/
https://medium.com/@Scofield_Idehen/sending-emails-made-easy-integrating-nodemailer-with-reactjs-e8d0d04a595e 
How we’re using the internationalization libraries: https://javascript.plainenglish.io/react-localization-the-winner-is-i18next-i18nexus-b7cd9f14094e
