### ISSUE TITLE
[YI | TONY] Create & Edit Classes 

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#53]
### Task Description: 
It’s class time. Let’s lock in.
Create a new endpoint that will handle both creating and editing classes in the database. The classes should be created following the schema, with the roster initialized as an empty array. When editing the class, the endpoint should still receive all the data of the class object, including the data that won’t be changed, so it’s up to you to determine if a user is creating or editing a class. This means you’ll want to check if the class already exists in the database: 
If it does, then that means they’re editing class details, and you’ll want to replace/update the class in the database (make sure the roster stays the same!). 
If it doesn’t, then they’re creating a class, and you’ll want to add a new class to the database.
Right now, there’s no specific page to create or edit a class, but you can test that the endpoint works using Postman. (Note: make sure that when you’re testing editing a class’s details, you add data for all the other fields of the class as well). You don’t worry about making this endpoint add or remove a student from the roster - that is handled by a different endpoint!

### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] When creating a new class, does the number of documents in the classes collection increase by 1 and the new class shows up in the collection?
- [ ] When editing a class, does the number of documents in the classes collection stay the same and the class shows up in the collection with the updated edits?
- [ ] When editing a class with students in the roster array, does the roster array stay the same after editing the class?

### References and Resources:
MongoDB collection commands: https://www.mongodb.com/docs/manual/reference/method/js-collection/ 
Mongo Updating Documents: https://www.mongodb.com/docs/manual/tutorial/update-documents/
