### ISSUE TITLE
[CLAIRE | ARYAA] High Fidelity Home Page & Footer 

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#55]
### Task Description: 
🏠(home) page!
We want Home.jsx to look as close to this as possible, this time down to the fonts and colors:
<img width="311" alt="Screenshot 2024-11-23 at 2 35 01 PM" src="https://github.com/user-attachments/assets/7bb03bc0-66cb-4955-a502-5d5c31dac37c">
Don’t be intimidated - it seems like a lot, but you can use the existing styling for the Class and Level components. You will have to make your own Footer and “You are registered” Confirmation Component. 
The “Start Learning” button should direct to the sign-up page and the “Learn More” should direct to the about page. 

We also want to implement internationalization on this page. We’re using the i18next library with i18nexus, which is a site where we can add strings and they’ll be automatically translated using Google Translate. Each string is assigned a key which we can use to reference the translations in our code (we would definitely recommend reading/skimming the first reference for a more detailed description and images of how it all works). 
Go through the Home page and Footer component and for all text (including headers, paragraph text, and button text) create a key-value pair in i18nexus with the string (make sure the key name is somewhat descriptive), and replace the text in the code with the key. This is a little tedious, but once you change the language on the site using the dropdown, all the text on this page should now be in the language selected! Yay!

### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] Does the styling look like the Figma?
- [ ] When changing the language, does all the text on the Home page and Footer change to be in that language?

### References and Resources: 
[Figma]( https://www.figma.com/design/bQkMH2fS2NAYoWDlynDh1W/Dillar-Academy?node-id=1-1771&node-type=canvas&t=WqQL3joCTYiIjf3o-0)
CSS Flexbox: https://css-tricks.com/snippets/css/a-guide-to-flexbox/ 
How we’re using the internationalization libraries: https://javascript.plainenglish.io/react-localization-the-winner-is-i18next-i18nexus-b7cd9f14094e
