### ISSUE TITLE
[DONATELLO | FRANK] Further i18n & High-Fidelity About Page 

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#56]
### Task Description: 
We’re so global! 🌐Time to 1) make the site more accessible in all the different languages we’re offering and 2) tell people about Dillar Academy on a beautiful new high-fidelity page.
To implement internationalization, we’re using the i18next library with i18nexus, which is a site where we can add strings and they’ll be automatically translated using Google Translate. Each string is assigned a key which we can use to reference the translations in our code (we would definitely recommend reading/skimming the first reference for a more detailed description and images of how it all works). 
Right now, only the header of the About page has translations applied (which you can see in action by selecting a language in the navbar dropdown), BUT we want more of the text to have translations. Go through the About, Sign-up, Login, and Page not Found pages and for all text (including headers, paragraph text, input placeholders, and button text) create a key-value pair in i18nexus with the string (make sure the key name is somewhat descriptive), and replace the text in the code with the key. This is a little tedious, but once you change the language on the site using the dropdown, all the text on those pages should now be in the language selected! Yay!
Your second task is to style the About page to look more like the high-fidelity design in the Figma:
<img width="593" alt="Screenshot 2024-11-23 at 2 37 22 PM" src="https://github.com/user-attachments/assets/78f0e1ea-64c7-454f-8224-1fb702e22c71">
This should be pretty simple as the general layout is already there: all you need to do is get the smaller details (colors, image styling, the star icon from the icon pack mentioned on the \style page when you run localhost, etc.).

### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] When changing the language, does all the text on the site change to be in that language across all the pages?
- [ ] Does the About page styling look like the Figma?

### References and Resources: 
[Figma](https://www.figma.com/design/bQkMH2fS2NAYoWDlynDh1W/Dillar-Academy?node-id=1-1771&node-type=canvas&t=WqQL3joCTYiIjf3o-0 )
How we’re using the internationalization libraries: https://javascript.plainenglish.io/react-localization-the-winner-is-i18next-i18nexus-b7cd9f14094e 
Icon pack: https://react-icons.github.io/react-icons/icons/io5/
