### ISSUE TITLE
[TOGZHAN | YI | ARYAA] Drop Down Wrapper Component

### ISSUE THREAD

**Issue by lillian-tran** [JumboCode/dillar-academy#9]
### Task Description: 
You will create a wrapper for drop-down menus so we can generalize their use!
In “Dropdown.jsx” create a React component that when clicked will display a drop down menu.  You will need to take children as a prop to allow for different drop down links.
<img width="608" alt="Screenshot 2024-10-19 at 10 45 31 AM" src="https://github.com/user-attachments/assets/c29c0346-fec4-469a-9147-bb15ac7d11b3">
For reference, if you look at the ‘More’ on Dillar’s current website, you can see they have drop-downs for Level 5 and Conversation. The React component should be able to take in different numbers and text for the links - this is just an example. Don’t worry too much about the styling yet.
### References and Resources: 
https://codeburst.io/a-quick-intro-to-reacts-props-children-cb3d2fce4891 
https://medium.com/@nnpk0410/children-props-in-react-enhancing-component-composition-2e7465a1b5e3 
[Current Site](https://dillarenglish.wixsite.com/dillaracademy/about)
### Acceptance Criteria: 
- [ ] Did you link the ticket/issue number with your branch using the pull request template?
- [ ] Does the DropDown component take in a children prop that allows you to render links/elements within the component tags?
- [ ] Can the drop down be opened and closed?
